from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import management_utils.models

class Migration(migrations.Migration):
    initial=True
    dependencies=[migrations.swappable_dependency(settings.AUTH_USER_MODEL)]
    operations=[
      migrations.CreateModel(name='Category',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('name',models.CharField(max_length=80,unique=True)),('description',models.TextField(blank=True)),('active',models.BooleanField(default=True))]),
      migrations.CreateModel(name='Department',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('name',models.CharField(max_length=150,unique=True)),('code',models.CharField(max_length=20,unique=True)),('active',models.BooleanField(default=True))]),
      migrations.CreateModel(name='SubCategory',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('name',models.CharField(max_length=120)),('active',models.BooleanField(default=True)),('category',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='subcategories',to='management_utils.category'))]),
      migrations.CreateModel(name='ProblemType',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('name',models.CharField(max_length=150)),('active',models.BooleanField(default=True)),('subcategory',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='problem_types',to='management_utils.subcategory'))]),
      migrations.CreateModel(name='Profile',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('role',models.CharField(choices=[('student','Student'),('staff','Staff'),('officer','Department Officer'),('management','Management'),('admin','Administrator')],default='student',max_length=20)),('phone',models.CharField(blank=True,max_length=30)),('department',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name='profiles',to='management_utils.department')),('user',models.OneToOneField(on_delete=django.db.models.deletion.CASCADE,related_name='profile',to=settings.AUTH_USER_MODEL))]),
      migrations.CreateModel(name='ProblemReport',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('reference',models.CharField(editable=False,max_length=40,unique=True)),('anonymous',models.BooleanField(default=False)),('title',models.CharField(max_length=200)),('description',models.TextField()),('location',models.CharField(max_length=200)),('building',models.CharField(blank=True,max_length=200)),('landmark',models.CharField(blank=True,max_length=200)),('severity',models.CharField(choices=[('low','Low'),('medium','Medium'),('high','High'),('critical','Critical')],default='medium',max_length=20)),('latitude',models.DecimalField(blank=True,decimal_places=6,max_digits=9,null=True)),('longitude',models.DecimalField(blank=True,decimal_places=6,max_digits=9,null=True)),('status',models.CharField(choices=[('submitted','Submitted'),('review','Under Review'),('assigned','Assigned'),('progress','In Progress'),('resolved','Resolved'),('closed','Closed'),('rejected','Rejected')],default='submitted',max_length=20)),('created_at',models.DateTimeField(auto_now_add=True)),('updated_at',models.DateTimeField(auto_now=True)),('assigned_department',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name='assigned_reports',to='management_utils.department')),('assigned_officer',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name='assigned_problem_reports',to=settings.AUTH_USER_MODEL)),('category',models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,to='management_utils.category')),('problem_type',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.PROTECT,to='management_utils.problemtype')),('reporter',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name='problem_reports',to=settings.AUTH_USER_MODEL)),('subcategory',models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,to='management_utils.subcategory'))]),
      migrations.CreateModel(name='ProblemImage',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('image',models.ImageField(upload_to='problem_reports/%Y/%m/')),('caption',models.CharField(blank=True,max_length=200)),('uploaded_at',models.DateTimeField(auto_now_add=True)),('report',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='images',to='management_utils.problemreport'))]),
      migrations.CreateModel(name='ReportUpdate',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('old_status',models.CharField(blank=True,max_length=20)),('new_status',models.CharField(blank=True,max_length=20)),('note',models.TextField()),('created_at',models.DateTimeField(auto_now_add=True)),('author',models.ForeignKey(null=True,on_delete=django.db.models.deletion.SET_NULL,to=settings.AUTH_USER_MODEL)),('report',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='updates',to='management_utils.problemreport'))]),
      migrations.CreateModel(name='Notification',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('title',models.CharField(max_length=180)),('message',models.TextField()),('is_read',models.BooleanField(default=False)),('created_at',models.DateTimeField(auto_now_add=True)),('report',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.CASCADE,to='management_utils.problemreport')),('user',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='notifications',to=settings.AUTH_USER_MODEL))]),
      migrations.AddConstraint(model_name='subcategory',constraint=models.UniqueConstraint(fields=('category','name'),name='unique_subcategory')),
      migrations.AddConstraint(model_name='problemtype',constraint=models.UniqueConstraint(fields=('subcategory','name'),name='unique_problem_type')),
    ]
