services:
  - type: web
    name: uniben-ieprts
    runtime: python
    region: frankfurt
    plan: free
    buildCommand: ./build.sh
    startCommand: gunicorn problem_reporting.wsgi:application
    healthCheckPath: /
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: DATABASE_URL
        fromDatabase:
          name: uniben-ieprts-db
          property: connectionString
      - key: CSRF_TRUSTED_ORIGINS
        value: "https://uniben-ieprts.onrender.com"
      - key: DJANGO_SUPERUSER_USERNAME
        sync: false
      - key: DJANGO_SUPERUSER_EMAIL
        sync: false
      - key: DJANGO_SUPERUSER_PASSWORD
        sync: false

databases:
  - name: uniben-ieprts-db
    plan: free
    region: frankfurt
